### ISSUE TITLE
转换器自己会改变素材名称吗？

### ISSUE THREAD

**Issue by leogentleman** [yyued/SVGA-AEConverter#9]
设计师在导出SVGA的时候自己原先命名的图片名称都被替换成类似img1，img2这种格式了，请问转换器是否会自己改变素材名称？有方法可以避免吗？

**Comment by PonyCui** [comment]
直接使用 PNG 而不使用 PSD

**Comment by PonyCui** [comment]
是在哪个端播放上发现锯齿？
